// Generated by https://quicktype.io

export interface PlacesResponse {
    type:        string;
    features:    Feature[];
    attribution: string;
}

export interface Feature {
    type:       string;
    id:         string;
    geometry:   Geometry;
    properties: Properties;
}

export interface Geometry {
    type:        string;
    coordinates: number[];
}

export interface Properties {
    mapbox_id:        string;
    feature_type:     string;
    name:             string;
    coordinates:      Coordinates;
    place_formatted?: string;
    context:          Context;
    bbox?:            number[];
}

export interface Context {
    address?:      Address;
    street?:       Postcode;
    neighborhood?: Locality;
    postcode?:     Postcode;
    locality?:     Locality;
    place?:        Locality;
    region?:       Region;
    country:       Country;
}

export interface Address {
    mapbox_id:      string;
    address_number: string;
    street_name:    string;
    name:           string;
}

export interface Country {
    mapbox_id:            string;
    name:                 string;
    wikidata_id:          string;
    country_code:         string;
    country_code_alpha_3: string;
    translations:         Translations;
}

export interface Translations {
    es: Es;
}

export interface Es {
    language: Language;
    name:     string;
}

export enum Language {
    Es = "es",
}

export interface Locality {
    mapbox_id:    MapboxID;
    name:         Name;
    wikidata_id?: string;
    translations: Translations;
}

export enum MapboxID {
    DXJuOm1IeHBsYzpBNUtvUmc = "dXJuOm1ieHBsYzpBNUtvUmc",
    DXJuOm1IeHBsYzpFaTlLUmc = "dXJuOm1ieHBsYzpFaTlLUmc",
    DXJuOm1IeHBsYzpXbXhH = "dXJuOm1ieHBsYzpXbXhH",
}

export enum Name {
    LaMalvaRosa = "La Malva-Rosa",
    PobladosMarítimos = "Poblados Marítimos",
    València = "València",
}

export interface Postcode {
    mapbox_id: string;
    name:      string;
}

export interface Region {
    mapbox_id:         string;
    name:              string;
    wikidata_id:       string;
    region_code?:      string;
    region_code_full?: string;
    translations:      Translations;
}

export interface Coordinates {
    longitude: number;
    latitude:  number;
    accuracy?: string;
}
